---
# tasks file for joshrooz.ssh-key-rotation
- name: Generate a new ssh keypair on ansible controller host
  openssh_keypair:
    path: "{{ lookup('env','PWD') }}/{{ ssh_key_path }}"
    size: '{{ ssh_key_bits }}'
    owner: "{{ lookup('env', 'USER') }}"
    comment: '{{ ssh_key_comment }}'
  when: inventory_hostname == play_hosts[0] # only run once across the active inventory
  delegate_to: localhost

- name: Register our public keys
  set_fact:
    ssh_connection_key: "{{ lookup('file', lookup('env','PWD') + '/' + ssh_key_path + '.pub') }}"
    ssh_dummy_key: "{{ lookup('file', lookup('env','PWD') + '/' + dummy_key_path + '.pub') }}"

- name: Ensure that our public keys have been registered
  assert:
    that:
      - ssh_connection_key is defined
      - ssh_dummy_key is defined
    quiet: yes

- name: Add/update amk public key in remote authorized_keys file
  authorized_key:
    exclusive: '{{ exclusive | default(false, true) }}'
    user: '{{ ssh_host_user }}'
    state: present
    manage_dir: '{{ should_manage_dir | default(false, true) }}'
    key: '{{ ssh_connection_key }}'

- name: Remove default dummy key
  authorized_key:
    state: absent
    user: '{{ ssh_host_user }}'
    manage_dir: false
    key: '{{ ssh_dummy_key }}'
  when: not exclusive
